# This is a basic workflow to help you get started with Actions

name: install module

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main master ]
  pull_request:
    branches: [ main master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  installSetup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 setup.py install
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
